default_language_version:
  python: python3.9

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
  - id: isort
    args: ["--check", "--diff"]
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black
    args: ["--check", "--diff"]
- repo: https://github.com/mgedmin/check-manifest
  rev: "0.46"
  hooks:
  - id: check-manifest