description: Add given metrics to source config
tags:
  - Sources
parameters:
  - in: path
    name: source_id
    required: true
    description: id of the source
  - in: path
    name: config_item_id
    required: true
    description: id of the configuration item
requestBody:
  content:
    'application/json':
      schema:
        type: object
        properties:
          metrics:
            type: array
            items:
              $ref: "#/components/schemas/AddMetricItem"
responses:
  '200':
    description: name of the new active metrics
    content:
      application/json:
        schema:
          type: array
          items:
            type: string
produces:
  - application/json