description: TODO Get list of available metrics for a configuration item
tags:
- Sources
parameters:
- in: path
  name: source_id
  required: true
  description: id of the source
- in: path
  name: config_item_id
  required: true
  description: id of the configuration item
produces:
- application/json