description: Get configuration for source
tags:
- Sources
parameters:
- in: path
  name: source_id
  required: true
  description: id of the source
responses:
  '200':
    description: source global configuration
    content:
      application/json:
        schema:
          tyep: object
produces:
- application/json