description: Send configuration to source
tags:
- Sources
parameters:
- in: path
  name: source_id
  required: true
  description: id of the source
response:
  '200':
    description: status of the reconfiguration
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
              description: should be success
produces:
- application/json