description: Update settings of configuration item of the source
tags:
- Sources
parameters:
- in: path
  name: source_id
  required: true
  description: id of the source
- in: path
  name: config_item_id
  required: true
  description: id of the configuration item
requestBody:
  description: updated config for the config item
  content:
    'application/json':
      schema:
        type: object
responses:
  '200':
    description: the updated config item
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ConfigItem"
produces:
- application/json